# -*- coding: utf-8 -*-
"""DadosVendas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dBEeXGoa3AiOLy5K0neGu3OgLJUSqVNJ
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

df = pd.read_csv('/content/order_history_kaggle_data.csv')
df.head()

"""## Limpeza Dados

###Conversão de Datas
"""

df['Order Placed At'] = pd.to_datetime(df['Order Placed At'], format='%I:%M %p, %B %d %Y')
df.head()

"""### Limpeza da Coluna de Distância"""

df['Distance'] = df['Distance'].str.replace('km', '', regex=False)
df['Distance'] = df['Distance'].str.replace('<1', '0.5', regex=False)
df['Distance'] = df['Distance'].astype(float)
df.head()

"""### Criação de Variáveis (Feature Engineering)

Extrair Hora do Dia, Dia da Semana e Mês a partir da data do pedido.
"""

df['Order Time'] = df['Order Placed At'].dt.strftime('%H:%M:%S')
df['Order Date'] = df['Order Placed At'].dt.date
df.head()

df['Order Hour'] = df['Order Placed At'].dt.hour
df['Order Month'] = df['Order Placed At'].dt.month_name()
df.head()

"""Criar uma coluna de Desconto Total somando todos os campos de desconto disponíveis."""

df['Brand pack discount'] = pd.to_numeric(df['Brand pack discount'], errors='coerce').fillna(0)
df['Gold discount'] = pd.to_numeric(df['Gold discount'], errors='coerce').fillna(0)
df['Restaurant discount (Flat offs, Freebies & others)'] = pd.to_numeric(df['Restaurant discount (Flat offs, Freebies & others)'], errors='coerce').fillna(0)
df['Restaurant discount (Promo)'] = pd.to_numeric(df['Restaurant discount (Promo)'], errors='coerce').fillna(0)

df['Desconto Total'] = df['Brand pack discount'] + df['Gold discount'] + df['Restaurant discount (Flat offs, Freebies & others)'] + df['Restaurant discount (Promo)']
df.head()

"""### Padronização de Strings

Garantir que nomes de cidades e subzonas não tenham espaços extras ou variações de grafia.
"""

df['City'] = df['City'].str.strip().str.capitalize()
df['Subzone'] = df['Subzone'].str.strip().str.capitalize()
df.head()



"""## Análise Descritiva

### Volume de Pedidos

Volume de pedidos pelo tempo
"""

# Ensure 'Order Day of Week' column exists
df['Order Day of Week'] = df['Order Placed At'].dt.day_name()

# Order volume by month
month_order = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December']
monthly_orders = df['Order Month'].value_counts().reindex(month_order, fill_value=0)

print("\nVolume de pedidos por mês:")
print(monthly_orders[monthly_orders > 0]) # Display only months with orders

sns.barplot(
    x=monthly_orders[monthly_orders > 0].index,
    y=monthly_orders[monthly_orders > 0].values,
    color='royalblue'
)

plt.title('Volume de Pedidos por Mês')
plt.xlabel('Mês')
plt.ylabel('Número de Pedidos')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# Volume de pedidos por dia da semana
day_order = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
daily_orders = df['Order Day of Week'].value_counts().reindex(day_order, fill_value=0)

print("\nVolume de pedidos por dia da semana:")
print(daily_orders)

plt.figure(figsize=(10, 6))

sns.barplot(x=daily_orders.index, y=daily_orders.values, color='teal')

plt.title('Volume de Pedidos por Dia da Semana')
plt.xlabel('Dia da Semana')
plt.ylabel('Número de Pedidos')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

"""### Métricas Financeiras"""

average_order_total = df['Total'].mean()
average_subtotal = df['Bill subtotal'].mean()

print(f"Valor Médio Total Recebido (Total): ${average_order_total:,.2f}")
print(f"Valor Médio Total Sem Desconto (Bill Subtotal): ${average_subtotal:,.2f}")

"""### Logística

Dados como Distância Média, Tempo de Preparo (KPT) e Tempo de Espera do Entregador
"""

average_distance = df['Distance'].mean()
average_kpt_duration = df['KPT duration (minutes)'].mean()
average_rider_wait_time = df['Rider wait time (minutes)'].mean()

print(f"Distância Média: {average_distance:,.2f} km.")
print(f"Tempo de Preparo (KPT): Média de {average_kpt_duration:,.1f} minutos.")
print(f"Tempo de Espera do Entregador: Média de {average_rider_wait_time:,.1f} minutos.")

"""### Satisfação

A nota média e taxa de resposta
"""

average_rating = df['Rating'].mean()
rating_response_rate = df['Rating'].count() / len(df) * 100

print(f"Nota Média de Avaliação: {average_rating:,.2f} / 5.0")
print(f"Taxa de Resposta de Avaliação: {rating_response_rate:,.2f}%")

plt.figure(figsize=(8, 5))

sns.countplot(x='Rating', data=df, color='teal')

plt.title('Distribuição das Notas de Avaliação')
plt.xlabel('Nota de Avaliação')
plt.ylabel('Número de Avaliações')
plt.tight_layout()
plt.show()

# Re-display the average rating and response rate for context
average_rating = df['Rating'].mean()
rating_response_rate = df['Rating'].count() / len(df) * 100
print(f"\nNota Média de Avaliação: {average_rating:,.2f} / 5.0")
print(f"Taxa de Resposta de Avaliação: {rating_response_rate:,.2f}%")

"""### Status dos Pedido"""

order_status_counts = df['Order Status'].value_counts()

print("\nContagem de Status dos Pedidos (Tabela):")
print(order_status_counts)

# Gráfico 1: Status Geral
plt.figure(figsize=(10, 6))

sns.barplot(x=order_status_counts.index, y=order_status_counts.values, color='steelblue')

plt.title('Distribuição do Status dos Pedidos')
plt.xlabel('Status do Pedido')
plt.ylabel('Número de Pedidos')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

non_delivered_status = order_status_counts.drop('Delivered', errors='ignore')

print("\nContagem de Status dos Pedidos (Excluindo 'Delivered'):")
print(non_delivered_status)

# Gráfico 2: Status Excluindo Entregues
plt.figure(figsize=(10, 6))

sns.barplot(x=non_delivered_status.index, y=non_delivered_status.values, color='teal')

plt.title('Distribuição de Status dos Pedidos (Excluindo Pedidos Entregues)')
plt.xlabel('Status do Pedido')
plt.ylabel('Número de Pedidos')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

"""## Análises

### Análise de Sazonalidade e Horários de Pico:

Identificar quais horas do dia concentram o maior volume de vendas para otimizar o estoque e a equipe de cozinha.
"""

order_volume_by_hour = df['Order Hour'].value_counts().sort_index()

print("\nVolume de Pedidos por Hora do Dia:")
print(order_volume_by_hour)

plt.figure(figsize=(12, 6))

# legend=False remove a legenda automática que seria criada para os valores
sns.barplot(
    x=order_volume_by_hour.index,
    y=order_volume_by_hour.values,
    hue=order_volume_by_hour.values,
    palette='Blues',
    legend=False
)

plt.title('Volume de Pedidos por Hora do Dia')
plt.xlabel('Hora do Dia')
plt.ylabel('Número de Pedidos')
plt.xticks(rotation=0) # Horas costumam ficar melhores sem rotação se houver espaço
plt.tight_layout()
plt.show()

"""###Análise de Eficiência Operacional:

Correlacionar a Distance com o Rider wait time para entender se locais mais distantes causam gargalos logísticos.
"""

correlation_distance_rider_wait = df['Distance'].corr(df['Rider wait time (minutes)'])
print(f"Correlação entre Distância e Tempo de Espera do Entregador: {correlation_distance_rider_wait:,.2f}")

plt.figure(figsize=(10, 6))
sns.kdeplot(
    x='Distance',
    y='Rider wait time (minutes)',
    data=df,
    fill=True,
    thresh=0,
    levels=15,
    cmap='Blues'
)

plt.title('Mapa de Calor de Densidade (KDE)')
plt.xlabel('Distância (km)')
plt.ylabel('Tempo de Espera (minutos)')
plt.show()

plt.figure(figsize=(10, 6))

# s=10 diminui o tamanho dos pontos
# order=2 tenta capturar curvas se a relação não for perfeitamente linear
sns.regplot(
    x='Distance',
    y='Rider wait time (minutes)',
    data=df,
    scatter_kws={'alpha':0.1, 's':10},
    line_kws={'color':'red'},
    lowess=True  # Cria uma linha que segue melhor a tendência local (suavizada)
)

plt.title('Tendência Suavizada: Distância vs. Tempo de Espera')
plt.grid(True, linestyle='--', alpha=0.3)
plt.show()

"""Verificar se o tempo de preparo (KPT) aumenta em dias de alto volume."""

average_kpt_by_day = df.groupby('Order Day of Week')['KPT duration (minutes)'].mean().reindex(day_order)
print("\nAverage KPT Duration by Day of the Week:")
print(average_kpt_by_day)

"""###Análise de Descontos e Rentabilidade:

Calcular o impacto dos descontos (Gold, Brand pack, Promo) no valor final.



"""

average_impact_on_final_value = (df['Bill subtotal'] - df['Total']).mean()

print(f"Valor Médio do Impacto dos Descontos no Valor Final (Bill subtotal - Total): ${average_impact_on_final_value:,.2f}")

"""###Verificar se pedidos com maiores descontos resultam em melhores avaliações (Rating)."""

correlation_discount_rating = df['Desconto Total'].corr(df['Rating'])
print(f"Correlação entre 'Desconto Total' e 'Rating': {correlation_discount_rating:,.2f}")

plt.figure(figsize=(10, 6))

# x_jitter e y_jitter espalham os pontos levemente para mostrar densidade
sns.regplot(
    x='Desconto Total',
    y='Rating',
    data=df,
    x_jitter=0.1,
    y_jitter=0.1,
    scatter_kws={'alpha':0.2, 's':10},
    line_kws={'color':'red'}
)

plt.title('Relação entre Desconto e Avaliação (com Jitter)')
plt.grid(True, linestyle='--', alpha=0.3)
plt.show()

plt.figure(figsize=(10, 6))

# Violin plot mostra a distribuição (largura) do desconto para cada nota
sns.violinplot(x='Rating', y='Desconto Total', data=df, color='steelblue', inner='quartile')

plt.title('Distribuição de Desconto por Nota de Avaliação')
plt.show()

plt.figure(figsize=(10, 6))

# x_bins divide o desconto em 10 partes e mostra a média e o intervalo de confiança
sns.regplot(
    x='Desconto Total',
    y='Rating',
    data=df,
    x_bins=10,
    color='steelblue',
    line_kws={'color':'red'}
)

plt.title('Média de Rating por Faixa de Desconto')
plt.show()

"""###Comportamento do Cliente:

Analisar a recorrência de Customer ID para identificar clientes fiéis e criar estratégias de retenção.
"""

customer_recurrence = df['Customer ID'].value_counts()

print("\nDistribuição da Recorrência de Pedidos por Cliente:")
print(customer_recurrence.value_counts().sort_index())

# Display top 10 most frequent customers
print("\nTop 10 Clientes Mais Frequentes:")
print(customer_recurrence.head(10))

"""###Análise de Cancelamentos e Reclamações:

Investigar os motivos em Cancellation / Rejection reason para reduzir perdas operacionais.

"""

cancellation_rejection_reasons = df['Cancellation / Rejection reason'].value_counts(dropna=True)

print("\nMotivos de Cancelamento / Rejeição:")
print(cancellation_rejection_reasons)

plt.figure(figsize=(10, 6))

# Trocado palette='coolwarm' por color='steelblue'
sns.barplot(
    x=cancellation_rejection_reasons.index,
    y=cancellation_rejection_reasons.values,
    color='steelblue'
)

plt.title('Distribuição dos Motivos de Cancelamento / Rejeição')
plt.xlabel('Motivo')
plt.ylabel('Número de Ocorrências')

# O ha='right' ajuda muito na legibilidade quando os nomes dos motivos são longos
plt.xticks(rotation=45, ha='right')

plt.tight_layout()
plt.show()

"""
###Análise de sentimentos básica nos textos da coluna Review."""

from textblob import TextBlob

def get_sentiment(text):
    if pd.isna(text):
        return None
    analysis = TextBlob(str(text))
    return analysis.sentiment.polarity

df['Sentiment_Polarity'] = df['Review'].apply(get_sentiment)

# Classify sentiment as Positive, Negative, or Neutral
def classify_sentiment(polarity):
    if polarity is None:
        return 'None'
    elif polarity > 0:
        return 'Positive'
    elif polarity < 0:
        return 'Negative'
    else:
        return 'Neutral'

df['Sentiment'] = df['Sentiment_Polarity'].apply(classify_sentiment)

print("\nAnálise de Sentimentos:")
print(f"Média da Polaridade do Sentimento: {df['Sentiment_Polarity'].mean():.2f}")
print("\nDistribuição do Sentimento:")
print(df['Sentiment'].value_counts())

plt.figure(figsize=(8, 5))

# Criamos o objeto 'ax' para conseguir acessar as barras e colocar os rótulos
ax = sns.countplot(
    x='Sentiment',
    data=df,
    color='steelblue',
    order=['Positive', 'Neutral', 'Negative', 'None']
)

# Adiciona os valores acima das barras
# padding=3 define a distância entre o topo da barra e o texto
ax.bar_label(ax.containers[0], padding=3)

plt.title('Distribuição do Sentimento das Avaliações')
plt.xlabel('Sentimento')
plt.ylabel('Número de Avaliações')

# Aumenta o limite do eixo Y um pouco para o texto não ficar cortado no topo
plt.margins(y=0.1)

plt.tight_layout()
plt.show()